version: '3'

setvices:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    containar_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1433
      - MSSQL_LCID=1041
      - TZ="Asia/Tokyo"
      - Japanese_CI_AS=Japanese_CI_AS
    ports:
      - 1433:1433
    volumes:
      - ./initdb.d:docker-initdb.d
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
      - mssql_secrets:/var/opt/mssql/secrets
    command: ["/bin/bash", "-c", "chmod +x /docker-initdb.d/entrypoint.sh && /docker-initdb.d/entrypoint.sh"]
volumes:
  mssql_data:
  mssql_log:
  mssql_secrets:
